### ISSUE TITLE
add commands in serviceprovider see comment

### ISSUE THREAD

**Issue by filipveschool** [digitaldreams/laracrud#17]
Hi, didn't wanna create a pull request otherwise I have to fork your repository and dont want that.

You can register your commands by doing like is done in my package. Use it as an example:

https://github.com/filipveschool/packagegenerator/blob/master/src/PackagerServiceProvider.php

I hope this is clear and can help you. It is not a very good package if people have to register the commands by themself is it :) ;).

**Comment by digitaldreams** [comment]
Thanks for your advice. I will follow
