### ISSUE TITLE
Is it possible to support multiple database configuration???

### ISSUE THREAD

**Issue by alextesi** [digitaldreams/laracrud#26]
I have to connect an external database and I thanked that I can create all model with your tool but i don't see the possibility to choose the database.
Have you a plan to implement it?
Thanks
Alessandro

**Comment by digitaldreams** [comment]
Really i do not have plan to choose database other than MySql. 

Here is my quick tips that can help you. 
First of you should convert your existing schema into MySql schema. 
Then connect that MySlq schema when you are in development mode. 
Once done then you can move back to your original schema.

**Comment by alextesi** [comment]
Thanks for your answer.
Sorry for my bad explanation.

All my database are mysql and i have more then one database configured in the same application.
Is there a way to choose a second configured mysql database?

Thanks
Alessandro

**Comment by digitaldreams** [comment]
Sorry currently it use default connection. 
I will make support for multiple connections too in my next major version 4.0
