### ISSUE TITLE
Call to undefined functions

### ISSUE THREAD

**Issue by muhammadatt** [digitaldreams/laracrud#28]
Running Laravel 6, PHP Version 7.2 I received the following errors when trying to use Laracrud:

> php artisan laracrud:model users

Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function LaraCrud\Helpers\str_singular() at C:\laragon\www\goalsetter\vendor\digitaldream\laracrud\src\lara-crud\Helpers\Helper.php:87

> php artisan laracrud:controller UserSettings

 Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function LaraCrud\Crud\camel_case() at C:\laragon\www\goalsetter\vendor\digitaldream\laracrud\src\lara-crud\Crud\Controller.php:185

**Comment by digitaldreams** [comment]
Thanks @muhammadatt for letting me know. 
Which laracrud version you are using  3.4?
Can you please try with 4.0 and let me know.

**Comment by abergo** [comment]
I get the same error with 4.0

**Comment by digitaldreams** [comment]
Thanks for letting me know. I have not tested yet on Laravel 6. I will let you know when it fixed.

**Comment by digitaldreams** [comment]
Hi @muhammadatt 
I just fixed this issue on version 4.0.1
Let me know if is not fixed yet

**Comment by githubmarau** [comment]
`vendor/digitaldream/laracrud/src/lara-crud/Crud/MigrationCrud.php`   <<-- this class

`namespace LaraCrud\Crud;

use Illuminate\Support\Str;  <<---  Add
use LaraCrud\Contracts\Crud;
use LaraCrud\Helpers\Helper;
use LaraCrud\Helpers\TemplateManager;
use DbReader\Table;
`

    `    /**
     * Generate Class Name
     *
     * @param $table
     * @return string
     * @throws \Exception
     */
    public function generateClassName($table)
    {
        // $class = 'create' . ucfirst(camel_case($table)) . 'Table';
        $class = 'create' . ucfirst(Str::camel($table)) . 'Table';  // <<---- change here

        if (class_exists($class)) {
            throw new \Exception('Migration for table ' . $table . ' already exists');
        }
        return $class;
    }`
